import { type NextPage } from "next";
import Head from "next/head";


const App: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <NavBar />
      </header>
      <main className="flex min-h-screen flex-col bg-neutral-900">
        <Jumbotron />
        <section className="p-12 text-center relative overflow-hidden bg-no-repeat bg-cover rounded-lg grid lg:grid-cols-3 md:grid-cols-1 gap-4">
          <div className="col-span-3">
            <h2 className="text-xl text-white mb-4">AAA</h2>
            <hr className="w-40 mx-auto border-t-2 border-gray-400 mt-6 mb-6" />
          </div>
          <div className="col-span-1">
            <Card
              title="Sign in/up"
              text="We support sign-in with GitHub, GitLab or Bitbucket"
              buttonText="Get started" />
          </div>
          <div className="col-span-1">
            <Card
              title="Train your first microclassifier"
              text="Provide your training data as a CSV file mapping documents to classes"
              buttonText="See supported formats" />
          </div>
          <div className="col-span-1">
            <Card
              title="Use your trained model"
              text="Query your model using our simple HTTP REST API"
              buttonText="Read the docs" />
          </div>
        </section>
      </main>
    </>
  );
};

export default App;

