import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";

import NavBar from "../components/navbar";
import Jumbotron from "../components/jumbotron";
import { getAbsoluteTop } from "../utils/spatial";
import Card from "../components/card";
import StaticImageCard from "../components/staticImageCard";
import AnimatedImageCard from "../components/animatedImageCard";
import { useRef } from "react";
import NavItem from "../components/navItem";
import SignedInNavItem from "../components/SignedInNavItem";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  const quickstartSection = useRef(null);
  const trainingSection = useRef(null);
  const usageSection = useRef(null);

  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <NavBar>
          <>
            <NavItem text="Home" onClick={() => window.scrollTo({
              top: 0,
              behavior: "smooth",
            })} />
            <NavItem text="Quickstart" onClick={() => window.scrollTo({
              top: getAbsoluteTop(quickstartSection.current),
              behavior: "smooth",
            })} />
            <NavItem text="Training" onClick={() => window.scrollTo({
              top: getAbsoluteTop(trainingSection.current),
              behavior: "smooth",
            })} />
            <NavItem text="Usage" onClick={() => window.scrollTo({
              top: getAbsoluteTop(usageSection.current),
              behavior: "smooth",
            })} />
            {sessionData ?
              <SignedInNavItem sessionData={sessionData} /> :
              <NavItem text="Sign in" onClick={() => signIn()} />
            }
          </>
        </NavBar>
      </header>
      <main className="flex min-h-screen flex-col bg-neutral-900">
        <Jumbotron onButtonClick={() => window.scrollTo({
          top: getAbsoluteTop(quickstartSection.current),
          behavior: "smooth"
        })} />
        <section className="p-12 text-center relative overflow-hidden bg-no-repeat bg-cover rounded-lg grid lg:grid-cols-3 md:grid-cols-1 gap-4">
          <div className="lg:col-span-3 md:col-span-1">
            <h2 ref={quickstartSection} className="text-xl text-white mb-4">Quickstart</h2>
            <hr className="w-40 mx-auto border-t-2 border-gray-400 mt-6 mb-6" />
          </div>
          <div className="col-span-1">
            <StaticImageCard
              title="Sign in/up"
              text="We support sign-in with GitHub, GitLab or Bitbucket"
              imageSrc="/images/source-control.svg"
              imageAlt="GitHub, GitLab and Bitbucket logos"
              buttonText={sessionData ? "Already signed in" : "Register"}
              buttonDisabled={!!sessionData}
              onButtonClick={() => signIn()}
            />
          </div>
          <div className="col-span-1">
            <AnimatedImageCard
              title="Train your first microclassifier"
              text="Provide your training data as a CSV file mapping documents to classes"
              baseUrl="/images/animations/classifier-training/frame-#.svg"
              imageAlt="Animation of a Classr logo slowly filling up with colour from bottom to top"
              frameCount={10}
              frameDelay={500}
              buttonText="See supported formats"
              onButtonClick={() => window.scrollTo({
                top: getAbsoluteTop(trainingSection.current),
                behavior: "smooth"
              })} />
          </div>
          <div className="col-span-1">
            <AnimatedImageCard
              title="Use your trained model"
              text="Query your model using our simple HTTP REST API"
              baseUrl="/images/animations/classifier-use/frame-#.svg"
              imageAlt="Animation of a Classr logo flashing green and red from left to right"
              frameCount={2}
              frameDelay={500}
              buttonText="Read the docs" />
          </div>
        </section>
        <section className="p-12 text-center relative overflow-hidden bg-no-repeat bg-cover bg-neutral-800 rounded-lg grid lg:grid-cols-4 md:grid-cols-1 gap-4">
          <div className="lg:col-span-4 md:col-span-1">
            <h2 ref={trainingSection} className="text-xl text-white mb-4">Training</h2>
            <hr className="w-40 mx-auto border-t-2 border-gray-400 mt-6 mb-6" />
          </div>
          <div className="col-span-1">

          </div>
          <div className="col-span-1">
            <Image alt="" src="/images/training-data.png" width={800} height={100} />
          </div>
          <div className="col-span-1 text-left text-white pl-5">
            <p className="font-bold mb-3">
              Provide your training data to Classr as a 2-column CSV file.
            </p>
            <p>
              This file must have a &quot;label&quot; column containing class labels and a &quot;document&quot; column
              containing documents. A maximum file size of 4MB is supported for training your microclassifier.
            </p>
          </div>
          <div className="col-span-1">

          </div>
        </section>
        <section className="p-12 text-center relative overflow-hidden bg-no-repeat bg-cover rounded-lg grid lg:grid-cols-2 md:grid-cols-1 gap-4">
          <div className="lg:col-span-2 md:col-span-1">
            <h2 ref={usageSection} className="text-xl text-white mb-4">Usage</h2>
            <hr className="w-40 mx-auto border-t-2 border-gray-400 mt-6 mb-6" />
          </div>
          <div className="col-span-1">

          </div>
          <div className="col-span-1">

          </div>
        </section>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
